apiVersion: v1
kind: Service
metadata:
  name: nginx-react-calculator-service
spec:
  selector:
    app: nginx-react-calculator
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
