name: Deployment pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-and-build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test and build react app
        run: |
          yarn --cwd ./react-calculator install
          yarn --cwd ./react-calculator test a --watchAll=false
          yarn --cwd ./react-calculator build
        env:
          NODE_VERSION: 16.15.1

  build-and-push-image:
    name: Login to Docker Hub
    runs-on: ubuntu-latest
    needs: test-and-build-app
    steps:
      - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USR }}
        password: ${{ secrets.DOCKER_PSW }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USR }}/nginx-react-calculator:${{ github.run_number }}

