name: Deployment pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.1
      - name: Test and build app
        run: |
          cd react-calculator
          yarn install
          yarn test a --watchAll=false
          yarn build
        id: build
        continue-on-error: true
      - name: Archive production artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./react-calculator/build

  build-and-push-image:
    name: Build and push Docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Reuse build directory
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./react-calculator/build
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PSW }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USR }}/nginx-react-calculator
  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Authenticate with Google Cloud Platform
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          export_default_credentials: true
      - name: Configure gcloud CLI
        run: |
          gcloud container clusters get-credentials react-calculator-cluster --zone europe-west1-b
      - name: Deploy to Kubernetes
        uses: google-github-actions/deploy-to-gke@main
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          cluster_name: react-calculator-cluster
          location: europe-west1-b
          yaml_file: | 
            - kubernetes/deployment.yaml
            - kubernetes/loadbalancer.yaml
