name: Deployment pipeline

on:
  push:
    branches: [main]

jobs:

  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    # needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:

      - name: Authenticate with Google Cloud Platform
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SA_KEY }}

          # export_default_credentials: true
      - name: Configure gcloud CLI
        run: |
          gcloud container clusters get-credentials react-calculator-cluster --zone europe-west1-b
      - name: Deploy to Kubernetes
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          cluster_name: react-calculator-cluster
          location: europe-west1-b
          yaml_file: |
            - kubernetes/deployment.yaml
            - kubernetes/loadbalancer.yaml
