name: Deployment pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: app build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test and build react app
        run: |
          yarn --cwd ./react-calculator install
          yarn --cwd ./react-calculator test a --watchAll=false
          yarn --cwd ./react-calculator build
        env:
          NODE_VERSION: 16.15.1

  build-and-push-image:
    name: Login to Docker Hub
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PSW }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USR }}/nginx-react-calculator:${{ github.run_number }}

